/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;

public class AdministradorDeEntregables extends javax.swing.JFrame {
    public ArrayList <Casillero> casilleros;
    /**
     * Creates new form AdministradorDeEntregables
     */
    public AdministradorDeEntregables() {
        initComponents(); 
    }
    
    /**
     * Creates new form AdministradorDeEntregables and initialize the global ArrayList <Casillero> casilleros;
     * @param casilleros
     */
    public AdministradorDeEntregables(ArrayList <Casillero> casillero) {
        initComponents(); 
        this.casilleros=casillero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroupConsulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButtonContinuar = new javax.swing.JButton();
        jButtonAtrás = new javax.swing.JButton();
        jRadioButtonPendientes = new javax.swing.JRadioButton();
        jRadioButtonEntregados = new javax.swing.JRadioButton();
        jRadioButtonRecibidos = new javax.swing.JRadioButton();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        jLabelConsulta = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(780, 380));
        setMaximumSize(new java.awt.Dimension(335, 285));
        setPreferredSize(new java.awt.Dimension(300, 258));
        setResizable(false);
        setSize(new java.awt.Dimension(335, 285));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Administración de entregables"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jButtonAtrás.setText("Atrás");
        jPanel1.add(jButtonAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jRadioButtonPendientes.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroupConsulta.add(jRadioButtonPendientes);
        jRadioButtonPendientes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonPendientes.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonPendientes.setText("Artículos Pendientes");
        jRadioButtonPendientes.setOpaque(false);
        jPanel1.add(jRadioButtonPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, -1));

        jRadioButtonEntregados.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroupConsulta.add(jRadioButtonEntregados);
        jRadioButtonEntregados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonEntregados.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEntregados.setText("Artículos entregados");
        jRadioButtonEntregados.setOpaque(false);
        jPanel1.add(jRadioButtonEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, -1));

        jRadioButtonRecibidos.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroupConsulta.add(jRadioButtonRecibidos);
        jRadioButtonRecibidos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonRecibidos.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonRecibidos.setText("Artículos recibidos");
        jRadioButtonRecibidos.setOpaque(false);
        jPanel1.add(jRadioButtonRecibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jRadioButtonEstado.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroupConsulta.add(jRadioButtonEstado);
        jRadioButtonEstado.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButtonEstado.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEstado.setText("Estado de un casillero");
        jRadioButtonEstado.setOpaque(false);
        jPanel1.add(jRadioButtonEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));

        jLabelConsulta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelConsulta.setForeground(new java.awt.Color(204, 255, 255));
        jLabelConsulta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelConsulta.setText("Seleccione el tipo de consulta:");
        jPanel1.add(jLabelConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 241, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondo.jpg"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 240));

        bindingGroup.bind();

        setSize(new java.awt.Dimension(311, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        if(jRadioButtonEstado.isSelected()==true){
            EstadoCasillero ventanaCasillero= new EstadoCasillero();
            ventanaCasillero.setVisible(true);
            this.dispose();
        }
        if(jRadioButtonEntregados.isSelected()==true){
            ArtículosEntregados ventanaEntregados= new ArtículosEntregados();
            ventanaEntregados.setVisible(true);
            this.dispose();
        }
        if(jRadioButtonPendientes.isSelected()==true){
            ArtículosPendientes ventanaPendientes= new ArtículosPendientes();
            ventanaPendientes.setVisible(true);
            this.dispose();
        }
        if(jRadioButtonRecibidos.isSelected()==true){
            ArtículosRecibidos ventanaRecibidos= new ArtículosRecibidos();
            ventanaRecibidos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeEntregables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdministradorDeEntregables().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup buttonGroupConsulta;
    private javax.swing.JButton jButtonAtrás;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonEntregados;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JRadioButton jRadioButtonPendientes;
    private javax.swing.JRadioButton jRadioButtonRecibidos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
