/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ArtículosEntregados extends javax.swing.JFrame {
    public ArrayList <Casillero> casilleros;
    /**
     * Creates new form ArtículosEntregados
     */
    public ArtículosEntregados() {
        initComponents();
        jTableEntregados.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo artículo","Monto","Fecha"}));
        GUI.TableHelp popUp =new GUI.TableHelp();
        popUp.popupTable(jTableEntregados);
        
    }
    /**
     * Creates new form ArtículosEntregados with the global ArrayList <Casillero> casilleros;
     * @param casillero
     * @param casilleros
     */
    public ArtículosEntregados(ArrayList <Casillero> casillero) {
        this.casilleros=casillero;
        initComponents();
        jTableEntregados.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo artículo","Monto","Fecha"}));
        GUI.TableHelp popUp =new GUI.TableHelp();
        popUp.popupTable(jTableEntregados);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jDateChooserEntregados = new com.toedter.calendar.JDateChooser();
        jButtonClear = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jButtonFind = new javax.swing.JButton();
        jScrollPaneEntregados = new javax.swing.JScrollPane();
        jTableEntregados = new javax.swing.JTable();
        jButtonRegresar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(510, 310));
        setMaximumSize(new java.awt.Dimension(800, 349));
        setMinimumSize(new java.awt.Dimension(621, 349));
        setPreferredSize(new java.awt.Dimension(920, 410));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("Artículos entregados"), this, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDateChooserEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));

        jButtonClear.setText("Limpiar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabelFecha.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(204, 255, 255));
        jLabelFecha.setText("Ingrese la fecha de búsqueda:");
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonFind.setText("Buscar");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jScrollPaneEntregados.setForeground(new java.awt.Color(204, 204, 255));

        jTableEntregados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTableEntregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEntregados.setGridColor(new java.awt.Color(0, 102, 153));
        jTableEntregados.setOpaque(false);
        jTableEntregados.getTableHeader().setReorderingAllowed(false);
        jScrollPaneEntregados.setViewportView(jTableEntregados);

        jPanel1.add(jScrollPaneEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 680, 330));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 350, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondo2.0.jpg"))); // NOI18N
        Fondo.setText(" ");
        Fondo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 420));

        bindingGroup.bind();

        setSize(new java.awt.Dimension(938, 430));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        //Proceso para cambiar de ventanas
        AdministradorDeEntregables ventanaEntregables = new AdministradorDeEntregables();
        ventanaEntregables.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
       try{
            TableHelp SystemDate= new TableHelp();
            //Ocupo que Datos=... venga con los datos de mis compañeros
            String[][] Datos= {{"Juan Mata","Oro","Sobre","0.99","15/04/2018"},{"Mauricio Áviles","Platino","Electronico","1.20","15/04/2018"},{"Yossi Mejía","Normal","Silla de LoL","2.05",SystemDate.getSystemDate()},{"Mario Camacho","Oro","sobre","0.26","16/04/2018"},{"Yosua Díaz","Normal","Electrónicos","3.25",SystemDate.getSystemDate()},{"Jorge Gutiérrez","Platino","Gorro","1.26","16/04/2018"} };
            String[][] dataShow= new String[50][50];
            TableHelp mostrar= new TableHelp();
            String[][] newData = mostrar.showData(jTableEntregados, jDateChooserEntregados, Datos, dataShow );
            if(newData[0][0]==null){
                jTableEntregados.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo Artículo","Monto","Fecha"}));
                JOptionPane.showMessageDialog(this, "No hay datos disponibles");
            }
            else{ 
                TableHelp llenar= new TableHelp();
                llenar.showData(jTableEntregados, jDateChooserEntregados, Datos, dataShow );
            }
        }
        catch(Exception e){
            if( jDateChooserEntregados.getDate()==null){
                jTableEntregados.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo Artículo","Monto","Fecha"}));
                JOptionPane.showMessageDialog(this,"Elija una fecha válida");        
            }
        }
    }//GEN-LAST:event_jButtonFindActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTableEntregados.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo artículo","Monto","Fecha"}));
    }//GEN-LAST:event_jButtonClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArtículosEntregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArtículosEntregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArtículosEntregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArtículosEntregados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtículosEntregados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonRegresar;
    private com.toedter.calendar.JDateChooser jDateChooserEntregados;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneEntregados;
    private javax.swing.JTable jTableEntregados;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
