/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EstadoCasillero extends javax.swing.JFrame {
    public ArrayList <Casillero> casilleros;
    /**
     * Creates new form EstadoCasillero
     */
    public EstadoCasillero() {
        initComponents();
        jTableCasilleros.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Artículo","Tipo","Monto","Fecha"}));
        GUI.TableHelp popUp =new GUI.TableHelp();
        popUp.popupTable(jTableCasilleros);
    }
    
    /**
     * Creates new form EstadoCasillero
     * @param casilleros
     */
    public EstadoCasillero(ArrayList <Casillero> casillero) {
        initComponents();
        this.casilleros=casillero;
        jTableCasilleros.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Artículo","Tipo","Monto","Fecha"}));
        GUI.TableHelp popUp =new GUI.TableHelp();
        popUp.popupTable(jTableCasilleros);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCasilleros = new javax.swing.JTable();
        jTextFieldCasilleroID = new javax.swing.JTextField();
        jButtonFind = new javax.swing.JButton();
        jLabelCasillero = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estado de un casillero");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 310));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonClear.setText("Limpiar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, -1, -1));

        jTableCasilleros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTableCasilleros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTableCasilleros.setColumnSelectionAllowed(true);
        jTableCasilleros.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableCasilleros.setGridColor(new java.awt.Color(0, 0, 0));
        jTableCasilleros.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTableCasilleros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCasilleros);
        jTableCasilleros.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 530, 310));

        jTextFieldCasilleroID.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldCasilleroID.setText("Casillero o ID");
        jTextFieldCasilleroID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCasilleroIDMouseClicked(evt);
            }
        });
        jTextFieldCasilleroID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCasilleroIDActionPerformed(evt);
            }
        });
        jTextFieldCasilleroID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCasilleroIDKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldCasilleroID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));

        jButtonFind.setText("Buscar");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabelCasillero.setBackground(new java.awt.Color(204, 255, 255));
        jLabelCasillero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCasillero.setForeground(new java.awt.Color(204, 255, 255));
        jLabelCasillero.setText("Ingrese número de casillero");
        jPanel1.add(jLabelCasillero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, -1));

        jLabelID.setBackground(new java.awt.Color(0, 0, 0));
        jLabelID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(204, 255, 255));
        jLabelID.setText("/ ID del cliente:");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/fondo2.0.jpg"))); // NOI18N
        Fondo.setText(" ");
        Fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -2, 790, 390));

        setSize(new java.awt.Dimension(772, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        AdministradorDeEntregables ventanaEntregables = new AdministradorDeEntregables();
        ventanaEntregables.setVisible(true);
        this.dispose();           
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jTextFieldCasilleroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCasilleroIDActionPerformed
        // TODO add your handling code here:
                 
    }//GEN-LAST:event_jTextFieldCasilleroIDActionPerformed

    private void jTextFieldCasilleroIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCasilleroIDMouseClicked
        // TODO add your handling code here:
        jTextFieldCasilleroID.setText("");
    }//GEN-LAST:event_jTextFieldCasilleroIDMouseClicked

    private void jTextFieldCasilleroIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCasilleroIDKeyTyped
        char limit =evt.getKeyChar();
        if(Character.isLetter(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextFieldCasilleroID.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 &&(int)evt.getKeyChar()<=64 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextFieldCasilleroID.setCursor(null);
        }
    }//GEN-LAST:event_jTextFieldCasilleroIDKeyTyped

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTableCasilleros.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo artículo","Monto","Fecha"}));
        
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        try{
            TableHelp SystemDate= new TableHelp();
            //Ocupo que Datos=... venga con los datos de mis compañeros
            //String[][] Datos= {{"Juan Mata","Oro","Sobre","0.99","15/04/2018"},{"Mauricio Áviles","Platino","Electronico","1.20","15/04/2018"},{"Yossi Mejía","Normal","Silla de LoL","2.05",SystemDate.getSystemDate()},{"Mario Camacho","Oro","sobre","0.26","16/04/2018"},{"Yosua Díaz","Normal","Electrónicos","3.25",SystemDate.getSystemDate()},{"Jorge Gutiérrez","Platino","Gorro","1.26","16/04/2018"} };
            String[][] dataShow= new String[50][50];
            TableHelp mostrar= new TableHelp();                                 //los datos de abajo los obtengo de la función correspondiente en tableHelp
            String[][] newData = mostrar.showData(jTableCasilleros, CasilleroID, Datos, dataShow)
            if(newData[0][0]==null){
                c.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo Artículo","Monto","Fecha", "Pendiente"}));
                JOptionPane.showMessageDialog(this, "No hay datos disponibles");
            }
            else{ 
                TableHelp llenar= new TableHelp();
                llenar.showData(jTableCasilleros, jTextFieldCasilleroID.getText(), Datos, dataShow );
            }
        }
        catch(Exception e){
            if( jTextFieldCasilleroID.getText()==null){
                jTableCasilleros.setModel(new DefaultTableModel(null,new String[]{"Propietario","Nivel","Tipo Artículo","Monto","Fecha","Pendiente"}));
                JOptionPane.showMessageDialog(this,"No hay datos registrados");        
            }
        }
    }
    }//GEN-LAST:event_jButtonFindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCasillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCasillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCasillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCasillero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCasillero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelCasillero;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCasilleros;
    private javax.swing.JTextField jTextFieldCasilleroID;
    // End of variables declaration//GEN-END:variables
}
