package GUI;

import java.util.ArrayList;

public final class Menu_Principal extends javax.swing.JFrame {
    public ArrayList <Casillero> casilleros;
    
    public Menu_Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu Principal");   
    }
    public Menu_Principal(int cantidad,Counter objeto) {
        ArrayList <Casillero> casillero= new ArrayList(); 
        casillero = setCasilleros(cantidad,objeto);
        this.casilleros = casillero;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu Principal");       
    }
    public Menu_Principal(ArrayList<Casillero> casillero) {
        this.casilleros = casillero;
        verCasillero(casillero);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menu Principal");   
    }
          //this.casillero=casillero;
    public ArrayList setCasilleros(int cantidad,Counter objeto){
        ArrayList<Casillero> casillero = new ArrayList();
        int identificador=1000;
        for(int i=0; i<cantidad;i++){
            Casillero campo = new Casillero(identificador,objeto); 
            casillero.add(campo);
            identificador++;
        }
       return casillero;
    } 
    public void verCasillero(ArrayList<Casillero> casilleros){
        for(int i=0; i<casilleros.size();i++){
            System.out.println("identificadores"+casilleros.get(i).numero);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButtonTipoCambio = new javax.swing.JButton();
        jButtonAdminEntregables = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Administrador de clientes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jButtonTipoCambio.setText("Tipo de Cambio");
        jButtonTipoCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipoCambioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jButtonAdminEntregables.setText("Administrador de entregables");
        jButtonAdminEntregables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminEntregablesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdminEntregables, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(627, 336));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ArrayList <Casillero> casilleros= this.casilleros;
        
        Administrar_clientes obj = new Administrar_clientes(casilleros);
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonTipoCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipoCambioActionPerformed
        CompraVenta ventanaCompraVenta= new GUI.CompraVenta();
        ventanaCompraVenta.setVisible(true);
    }//GEN-LAST:event_jButtonTipoCambioActionPerformed

    private void jButtonAdminEntregablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminEntregablesActionPerformed
        AdministradorDeEntregables ventanaAdministradorEntregables= new AdministradorDeEntregables();
        ventanaAdministradorEntregables.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAdminEntregablesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAdminEntregables;
    private javax.swing.JButton jButtonTipoCambio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
