package GUI;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yosua
 */
public class Modificar_cliente extends javax.swing.JFrame {
    public ArrayList<Casillero> casillero;
    DefaultListModel lista = new DefaultListModel();
    /**
     * Creates new form Modificar_cliente
     */
    public Modificar_cliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Modificar Clientes");
    }
    public Modificar_cliente(ArrayList<Casillero> casillero) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Modificar Clientes");
        this.casillero = casillero;
        
        for(int i=0;i<casillero.size();i++){
            if(casillero.get(i).usuario != null){
                lista.addElement(casillero.get(i).usuario.identificacion);
                jList1.setModel(lista);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Identificacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 80, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, -1));

        jLabel4.setText("Correo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 60, -1));

        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 70, -1));

        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 80, -1));

        jLabel7.setText("Nivel:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 50, 20));

        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Modificar Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 50));

        jLabel10.setText("Selecione un cliente:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, -1));

        jScrollPane8.setViewportView(jList1);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 70));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 150, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 150, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 150, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 150, -1));

        jButton3.setText("Consultar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel11.setText("Fecha nacimiento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 120, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plata", "Oro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 150, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 150, -1));

        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyTyped(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 150, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 580));

        setSize(new java.awt.Dimension(647, 619));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON DE ACEPTAR
        try{
        String id = jTextField1.getText();
        String nombre = jTextField2.getText();
        String correo = jTextField3.getText();
        String telefono = jTextField4.getText();
        String direccion = jTextField5.getText();
        String sexo = jComboBox2.getSelectedItem().toString();
        String dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes+ "-" + dia);
        System.out.println(fecha);
        String nivel = jComboBox1.getSelectedItem().toString();
        System.out.println(fecha);
        String id1 = jList1.getSelectedValue();
        for (int i=0;i<this.casillero.size();i++){
            if(casillero.get(i).usuario != null){
                if(this.casillero.get(i).usuario.identificacion.equals(id1)){
                    this.casillero.get(i).usuario.setIdentificacion(id);
                    this.casillero.get(i).usuario.setNombre(nombre);
                    this.casillero.get(i).usuario.setCorreo(correo);
                    this.casillero.get(i).usuario.setTelefono(telefono);
                    this.casillero.get(i).usuario.setDireccion(direccion);
                    this.casillero.get(i).usuario.setSexo(sexo);
                    this.casillero.get(i).usuario.setFecha(fecha);
                    this.casillero.get(i).usuario.setNivel(nivel);
                }
            }
            
        }
        
        
        ArrayList<Casillero> casilleros = this.casillero;
        Administrar_clientes obj = new Administrar_clientes(casilleros);
        obj.setVisible(true);
        this.setVisible(false);
        }
        catch(Exception ee){
            showMessageDialog(null,"Llene todos los campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOTON DE CANCELAR 
        ArrayList<Casillero> carilleros = this.casillero;
        Administrar_clientes obj = new Administrar_clientes(carilleros);
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOTON DE CONSULTAR
        String id = jList1.getSelectedValue();
        System.out.println(id);
        for (int i=0;i<this.casillero.size();i++){
            System.out.println("entro");
            if(casillero.get(i).usuario != null){
                if(this.casillero.get(i).usuario.identificacion.equals(id)){
                    jTextField1.setText(this.casillero.get(i).usuario.identificacion);
                    jTextField2.setText(this.casillero.get(i).usuario.nombre);
                    jTextField3.setText(this.casillero.get(i).usuario.correo);
                    jTextField4.setText(this.casillero.get(i).usuario.telefono);
                    jTextField5.setText(this.casillero.get(i).usuario.direccion);
                    jComboBox1.setSelectedItem(this.casillero.get(i).usuario.nivel);
                    jComboBox2.setSelectedItem(this.casillero.get(i).usuario.sexo);
                    
                    SimpleDateFormat formatoDelTexto;
                    formatoDelTexto = new SimpleDateFormat("yyyy/MM/dd");
                    Date fecha = null;
                    try {

                    fecha = formatoDelTexto.parse(this.casillero.get(i).usuario.fecha);

                    } catch (ParseException ex) {
                    }
                    jDateChooser1.setDate(fecha);
                }
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isLetter(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField1.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 &&(int)evt.getKeyChar()<=64 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField1.setCursor(null);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isDigit(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField2.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=64 || (int)evt.getKeyChar()>=91 &&(int)evt.getKeyChar()<=96 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField2.setCursor(null);
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        
         
        char limit =evt.getKeyChar();
        if(Character.isDigit(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField3.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<46  || (int)evt.getKeyChar()>47 && (int)evt.getKeyChar()<64 || (int)evt.getKeyChar()>=91 &&(int)evt.getKeyChar()<=96 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField3.setCursor(null);
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isLetter(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField4.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 &&(int)evt.getKeyChar()<=64 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField4.setCursor(null);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jDateChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Windows (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
