package GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import static javafx.beans.binding.Bindings.and;
import javax.swing.JOptionPane;

import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yosua
 */
public class Registrar_cliente extends javax.swing.JFrame {
    public ArrayList <Casillero> casilleros;
    /**
     * Creates new form interfaz
     */
    public void verCasillero(ArrayList<Casillero> casilleros){
        for(int i=0; i<casilleros.size();i++){
            System.out.println("identificadores"+casilleros.get(i).numero);
        }
    }
    public Registrar_cliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar Cliente");
    }
    public Registrar_cliente(ArrayList<Casillero> casillero) {
        this.casilleros = casillero;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar Cliente");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Identificacion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 80, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 70, -1));

        jLabel4.setText("Correo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 60, -1));

        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 70, -1));

        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, -1));

        jLabel7.setText("Fecha nacimiento:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 120, 20));

        jLabel8.setText("Sexo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 540, -1, -1));

        jLabel9.setText("Registrar Cliente");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jTextField1.setToolTipText("");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 150, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 150, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 150, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 150, -1));

        jTextField5.setForeground(new java.awt.Color(204, 204, 255));
        jTextField5.setText("CIUDAD");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 150, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\yosua\\OneDrive\\Documentos\\NetBeansProjects\\prueba\\fondo.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 630));

        setSize(new java.awt.Dimension(640, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOTON DE ACEPTAR 
        try{
        String id = jTextField1.getText();
        //int int_id = Integer.parseInt(id);
        String nombre = jTextField2.getText();
        String correo = jTextField3.getText();
        String telefono = jTextField4.getText();
        String direccion = jTextField5.getText();
        String sexo = jComboBox1.getSelectedItem().toString();
        //String fecha = jTextField7.getText();
        String dia = Integer.toString(jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jDateChooser1.getCalendar().get(Calendar.MONTH) + 1);
        String year = Integer.toString(jDateChooser1.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes+ "-" + dia);
        String existe = "NO";
        
        
        for(int i=0;i<this.casilleros.size();i++){
            if(casilleros.get(i).usuario != null){
                if(casilleros.get(i).usuario.identificacion.equals(id) ){
                    existe = "SI";
                }
            }
        }
        System.out.println(existe);
        int limite= casilleros.size();
        System.out.println(limite);
        if(existe.equals("NO")){
            ArrayList<Articulo> paquetes = new ArrayList();
            Usuario nuevo_usuario = new Usuario(id,nombre,correo,telefono,direccion,sexo,fecha,paquetes,0);
            System.out.println(nuevo_usuario.fecha);
            for(int i=0;i<this.casilleros.size();i++){
                if(this.casilleros.get(i).usuario == null ){
                    this.casilleros.get(i).usuario = nuevo_usuario;
                    System.out.println("Usuario insertado");
                    JOptionPane.showMessageDialog(null, "Usuario Insertado");
                    break;
                }
                if(i+1==limite){
                    System.out.println("Casilleros llenos");
                    JOptionPane.showMessageDialog(null, "Casilleros llenos");
                    break;
                }
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Usuario Existente");
        }
        
        
        Administrar_clientes obj = new Administrar_clientes(this.casilleros);
        obj.setVisible(true);
        this.setVisible(false);
        }catch(Exception ee){
            showMessageDialog(null,"Llene todos los campos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOTON DE CANCELAR
        ArrayList<Casillero> casillero = this.casilleros;
        Administrar_clientes obj = new Administrar_clientes(casillero);
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // IDENTIFICACION:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        
        char limit =evt.getKeyChar();
        if(Character.isLetter(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField1.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 &&(int)evt.getKeyChar()<=64 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField1.setCursor(null);
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isDigit(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField2.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=64 || (int)evt.getKeyChar()>=91 &&(int)evt.getKeyChar()<=96 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField2.setCursor(null);
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isLetter(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField4.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47 || (int)evt.getKeyChar()>=58 &&(int)evt.getKeyChar()<=64 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar números");
            jTextField4.setCursor(null);
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char limit =evt.getKeyChar();
        if(Character.isDigit(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField5.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=64 || (int)evt.getKeyChar()>=91 &&(int)evt.getKeyChar()<=96 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField5.setCursor(null);
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        jTextField5.setText("");
        jTextField5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        
        char limit =evt.getKeyChar();
        if(Character.isDigit(limit)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField3.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<46  || (int)evt.getKeyChar()>47 && (int)evt.getKeyChar()<64 || (int)evt.getKeyChar()>=91 &&(int)evt.getKeyChar()<=96 ||(int)evt.getKeyChar()>=123 &&(int)evt.getKeyChar()<=126){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this,"Solo puede ingresar caracteres alfabéticos");
            jTextField3.setCursor(null);
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
